/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EmailCapabilitiesDto,
    EmailCapabilitiesDtoFromJSON,
    EmailCapabilitiesDtoToJSON,
} from '../models/EmailCapabilitiesDto';

/**
 * 
 */
export class AccountEmailApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEmailCapabilities without sending the request
     */
    async getEmailCapabilitiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/account/email-capabilities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reports whether transactional email-backed account workflows are available.
     */
    async getEmailCapabilitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailCapabilitiesDto>> {
        const requestOptions = await this.getEmailCapabilitiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailCapabilitiesDtoFromJSON(jsonValue));
    }

    /**
     * Reports whether transactional email-backed account workflows are available.
     */
    async getEmailCapabilities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailCapabilitiesDto> {
        const response = await this.getEmailCapabilitiesRaw(initOverrides);
        return await response.value();
    }

}
