/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GroupDto,
  GroupInputDto,
  GroupJoinLinkDto,
  GroupReducedDto,
  ProblemDetails,
  TransactionDto,
  UploadImageResult,
} from '../models/index';
import {
    GroupDtoFromJSON,
    GroupDtoToJSON,
    GroupInputDtoFromJSON,
    GroupInputDtoToJSON,
    GroupJoinLinkDtoFromJSON,
    GroupJoinLinkDtoToJSON,
    GroupReducedDtoFromJSON,
    GroupReducedDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TransactionDtoFromJSON,
    TransactionDtoToJSON,
    UploadImageResultFromJSON,
    UploadImageResultToJSON,
} from '../models/index';

export interface AddGroupMemberRequest {
    groupId: string;
    requestBody?: Array<string>;
}

export interface CreateGroupRequest {
    groupInputDto?: GroupInputDto;
}

export interface CreateGroupJoinLinkRequest {
    groupId: string;
}

export interface DeleteGroupRequest {
    groupId: string;
}

export interface GetGroupRequest {
    groupId: string;
}

export interface GetGroupInfoByLinkRequest {
    joinLinkId: string;
}

export interface GetGroupTransactionsRequest {
    groupId: string;
}

export interface JoinGroupByLinkRequest {
    joinLinkId: string;
}

export interface UpdateGroupRequest {
    groupId: string;
    groupInputDto?: GroupInputDto;
}

export interface UploadGroupAvatarRequest {
    groupId: string;
    file?: Blob;
}

/**
 * 
 */
export class GroupApi extends runtime.BaseAPI {

    /**
     * Creates request options for addGroupMember without sending the request
     */
    async addGroupMemberRequestOpts(requestParameters: AddGroupMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling addGroupMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}/members`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Add members to a group
     */
    async addGroupMemberRaw(requestParameters: AddGroupMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDto>> {
        const requestOptions = await this.addGroupMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDtoFromJSON(jsonValue));
    }

    /**
     * Add members to a group
     */
    async addGroupMember(requestParameters: AddGroupMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDto> {
        const response = await this.addGroupMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGroup without sending the request
     */
    async createGroupRequestOpts(requestParameters: CreateGroupRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupInputDtoToJSON(requestParameters['groupInputDto']),
        };
    }

    /**
     * Create a new group
     */
    async createGroupRaw(requestParameters: CreateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDto>> {
        const requestOptions = await this.createGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDtoFromJSON(jsonValue));
    }

    /**
     * Create a new group
     */
    async createGroup(requestParameters: CreateGroupRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDto> {
        const response = await this.createGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createGroupJoinLink without sending the request
     */
    async createGroupJoinLinkRequestOpts(requestParameters: CreateGroupJoinLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling createGroupJoinLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}/join-link`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * create a join link for a group
     */
    async createGroupJoinLinkRaw(requestParameters: CreateGroupJoinLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupJoinLinkDto>> {
        const requestOptions = await this.createGroupJoinLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupJoinLinkDtoFromJSON(jsonValue));
    }

    /**
     * create a join link for a group
     */
    async createGroupJoinLink(requestParameters: CreateGroupJoinLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupJoinLinkDto> {
        const response = await this.createGroupJoinLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteGroup without sending the request
     */
    async deleteGroupRequestOpts(requestParameters: DeleteGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling deleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a group.
     */
    async deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a group.
     */
    async deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGroupRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getGroup without sending the request
     */
    async getGroupRequestOpts(requestParameters: GetGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the group info
     */
    async getGroupRaw(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDto>> {
        const requestOptions = await this.getGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDtoFromJSON(jsonValue));
    }

    /**
     * Get the group info
     */
    async getGroup(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDto> {
        const response = await this.getGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupInfoByLink without sending the request
     */
    async getGroupInfoByLinkRequestOpts(requestParameters: GetGroupInfoByLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['joinLinkId'] == null) {
            throw new runtime.RequiredError(
                'joinLinkId',
                'Required parameter "joinLinkId" was null or undefined when calling getGroupInfoByLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/join/{joinLinkId}`;
        urlPath = urlPath.replace(`{${"joinLinkId"}}`, encodeURIComponent(String(requestParameters['joinLinkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get group info from join link
     */
    async getGroupInfoByLinkRaw(requestParameters: GetGroupInfoByLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupReducedDto>> {
        const requestOptions = await this.getGroupInfoByLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupReducedDtoFromJSON(jsonValue));
    }

    /**
     * get group info from join link
     */
    async getGroupInfoByLink(requestParameters: GetGroupInfoByLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupReducedDto> {
        const response = await this.getGroupInfoByLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroupTransactions without sending the request
     */
    async getGroupTransactionsRequestOpts(requestParameters: GetGroupTransactionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling getGroupTransactions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}/transactions`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the group transactions
     */
    async getGroupTransactionsRaw(requestParameters: GetGroupTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TransactionDto>>> {
        const requestOptions = await this.getGroupTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionDtoFromJSON));
    }

    /**
     * Get the group transactions
     */
    async getGroupTransactions(requestParameters: GetGroupTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TransactionDto>> {
        const response = await this.getGroupTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroups without sending the request
     */
    async getGroupsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current user\'s groups
     */
    async getGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupDto>>> {
        const requestOptions = await this.getGroupsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupDtoFromJSON));
    }

    /**
     * Get the current user\'s groups
     */
    async getGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupDto>> {
        const response = await this.getGroupsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for joinGroupByLink without sending the request
     */
    async joinGroupByLinkRequestOpts(requestParameters: JoinGroupByLinkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['joinLinkId'] == null) {
            throw new runtime.RequiredError(
                'joinLinkId',
                'Required parameter "joinLinkId" was null or undefined when calling joinGroupByLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/join/{joinLinkId}`;
        urlPath = urlPath.replace(`{${"joinLinkId"}}`, encodeURIComponent(String(requestParameters['joinLinkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * join a group by a join link
     */
    async joinGroupByLinkRaw(requestParameters: JoinGroupByLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDto>> {
        const requestOptions = await this.joinGroupByLinkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDtoFromJSON(jsonValue));
    }

    /**
     * join a group by a join link
     */
    async joinGroupByLink(requestParameters: JoinGroupByLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDto> {
        const response = await this.joinGroupByLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGroup without sending the request
     */
    async updateGroupRequestOpts(requestParameters: UpdateGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/group/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GroupInputDtoToJSON(requestParameters['groupInputDto']),
        };
    }

    /**
     * Update group info
     */
    async updateGroupRaw(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupDto>> {
        const requestOptions = await this.updateGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupDtoFromJSON(jsonValue));
    }

    /**
     * Update group info
     */
    async updateGroup(requestParameters: UpdateGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupDto> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadGroupAvatar without sending the request
     */
    async uploadGroupAvatarRequestOpts(requestParameters: UploadGroupAvatarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling uploadGroupAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/group/{groupId}/avatar`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload a group avatar image.
     */
    async uploadGroupAvatarRaw(requestParameters: UploadGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadImageResult>> {
        const requestOptions = await this.uploadGroupAvatarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadImageResultFromJSON(jsonValue));
    }

    /**
     * Upload a group avatar image.
     */
    async uploadGroupAvatar(requestParameters: UploadGroupAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadImageResult> {
        const response = await this.uploadGroupAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
