/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InvoiceDto,
  InvoiceInputDto,
  InvoiceReducedDto,
  InvoiceSettlementDto,
  InvoiceSettlementInputDto,
  ProblemDetails,
} from '../models/index';
import {
    InvoiceDtoFromJSON,
    InvoiceDtoToJSON,
    InvoiceInputDtoFromJSON,
    InvoiceInputDtoToJSON,
    InvoiceReducedDtoFromJSON,
    InvoiceReducedDtoToJSON,
    InvoiceSettlementDtoFromJSON,
    InvoiceSettlementDtoToJSON,
    InvoiceSettlementInputDtoFromJSON,
    InvoiceSettlementInputDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface AddSettlementRequest {
    id: string;
    invoiceSettlementInputDto?: InvoiceSettlementInputDto;
}

export interface CreateInvoiceRequest {
    invoiceInputDto?: InvoiceInputDto;
}

export interface DeleteInvoiceRequest {
    id: string;
}

export interface DeleteSettlementRequest {
    id: string;
    settlementId: string;
}

export interface GetInvoiceRequest {
    id: string;
}

export interface UpdateInvoiceRequest {
    id: string;
    invoiceInputDto?: InvoiceInputDto;
}

/**
 * 
 */
export class InvoiceApi extends runtime.BaseAPI {

    /**
     * Creates request options for addSettlement without sending the request
     */
    async addSettlementRequestOpts(requestParameters: AddSettlementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addSettlement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice/{id}/settlement`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceSettlementInputDtoToJSON(requestParameters['invoiceSettlementInputDto']),
        };
    }

    /**
     * Record a settlement for an invoice
     */
    async addSettlementRaw(requestParameters: AddSettlementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceSettlementDto>> {
        const requestOptions = await this.addSettlementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceSettlementDtoFromJSON(jsonValue));
    }

    /**
     * Record a settlement for an invoice
     */
    async addSettlement(requestParameters: AddSettlementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceSettlementDto> {
        const response = await this.addSettlementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createInvoice without sending the request
     */
    async createInvoiceRequestOpts(requestParameters: CreateInvoiceRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceInputDtoToJSON(requestParameters['invoiceInputDto']),
        };
    }

    /**
     * Create an invoice from selected transactions in a group
     */
    async createInvoiceRaw(requestParameters: CreateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceDto>> {
        const requestOptions = await this.createInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceDtoFromJSON(jsonValue));
    }

    /**
     * Create an invoice from selected transactions in a group
     */
    async createInvoice(requestParameters: CreateInvoiceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceDto> {
        const response = await this.createInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteInvoice without sending the request
     */
    async deleteInvoiceRequestOpts(requestParameters: DeleteInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an invoice. Only the creator can delete.
     */
    async deleteInvoiceRaw(requestParameters: DeleteInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an invoice. Only the creator can delete.
     */
    async deleteInvoice(requestParameters: DeleteInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteInvoiceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSettlement without sending the request
     */
    async deleteSettlementRequestOpts(requestParameters: DeleteSettlementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSettlement().'
            );
        }

        if (requestParameters['settlementId'] == null) {
            throw new runtime.RequiredError(
                'settlementId',
                'Required parameter "settlementId" was null or undefined when calling deleteSettlement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice/{id}/settlement/{settlementId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"settlementId"}}`, encodeURIComponent(String(requestParameters['settlementId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a settlement from an invoice
     */
    async deleteSettlementRaw(requestParameters: DeleteSettlementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSettlementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a settlement from an invoice
     */
    async deleteSettlement(requestParameters: DeleteSettlementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSettlementRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getInvoice without sending the request
     */
    async getInvoiceRequestOpts(requestParameters: GetInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get invoice by id with debts, settlements, and transactions
     */
    async getInvoiceRaw(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceDto>> {
        const requestOptions = await this.getInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceDtoFromJSON(jsonValue));
    }

    /**
     * Get invoice by id with debts, settlements, and transactions
     */
    async getInvoice(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceDto> {
        const response = await this.getInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getInvoices without sending the request
     */
    async getInvoicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List invoices for the current user\'s groups
     */
    async getInvoicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InvoiceReducedDto>>> {
        const requestOptions = await this.getInvoicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InvoiceReducedDtoFromJSON));
    }

    /**
     * List invoices for the current user\'s groups
     */
    async getInvoices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InvoiceReducedDto>> {
        const response = await this.getInvoicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateInvoice without sending the request
     */
    async updateInvoiceRequestOpts(requestParameters: UpdateInvoiceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/invoice/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceInputDtoToJSON(requestParameters['invoiceInputDto']),
        };
    }

    /**
     * Update invoice transactions (add/remove). Recalculates debts.
     */
    async updateInvoiceRaw(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateInvoiceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update invoice transactions (add/remove). Recalculates debts.
     */
    async updateInvoice(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateInvoiceRaw(requestParameters, initOverrides);
    }

}
