/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ProblemDetails, TransactionDto, TransactionInputDto, UploadImageResult } from "../models/index";
import {
  ProblemDetailsFromJSON,
  ProblemDetailsToJSON,
  TransactionDtoFromJSON,
  TransactionDtoToJSON,
  TransactionInputDtoFromJSON,
  TransactionInputDtoToJSON,
  UploadImageResultFromJSON,
  UploadImageResultToJSON
} from "../models/index";
import * as runtime from "../runtime";

export interface AddTransactionRequest {
  transactionInputDto?: TransactionInputDto;
}

export interface DeleteTransactionRequest {
  id: string;
}

export interface GetTransactionRequest {
  id: string;
}

export interface UpdateTransactionRequest {
  transactionId: string;
  transactionInputDto?: TransactionInputDto;
}

export interface UploadTransactionReceiptRequest {
  id: string;
  file?: Blob;
}

/**
 *
 */
export class TransactionApi extends runtime.BaseAPI {
  /**
   * Add a transaction
   */
  async addTransactionRaw(
    requestParameters: AddTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TransactionDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("Bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/transaction`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: TransactionInputDtoToJSON(requestParameters["transactionInputDto"])
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
  }

  /**
   * Add a transaction
   */
  async addTransaction(
    requestParameters: AddTransactionRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TransactionDto> {
    const response = await this.addTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete a transaction
   */
  async deleteTransactionRaw(
    requestParameters: DeleteTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteTransaction().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("Bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/transaction/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a transaction
   */
  async deleteTransaction(
    requestParameters: DeleteTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteTransactionRaw(requestParameters, initOverrides);
  }

  /**
   * Get transaction by id
   */
  async getTransactionRaw(
    requestParameters: GetTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TransactionDto>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getTransaction().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("Bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/transaction/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDtoFromJSON(jsonValue));
  }

  /**
   * Get transaction by id
   */
  async getTransaction(
    requestParameters: GetTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TransactionDto> {
    const response = await this.getTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update a transaction
   */
  async updateTransactionRaw(
    requestParameters: UpdateTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError(
        "transactionId",
        'Required parameter "transactionId" was null or undefined when calling updateTransaction().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("Bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: TransactionInputDtoToJSON(requestParameters["transactionInputDto"])
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Update a transaction
   */
  async updateTransaction(
    requestParameters: UpdateTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.updateTransactionRaw(requestParameters, initOverrides);
  }

  /**
   * Upload a receipt image for a transaction.
   */
  async uploadTransactionReceiptRaw(
    requestParameters: UploadTransactionReceiptRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UploadImageResult>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling uploadTransactionReceipt().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("Bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["file"] != null) {
      formParams.append("file", requestParameters["file"] as any);
    }

    let urlPath = `/transaction/{id}/receipt`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UploadImageResultFromJSON(jsonValue));
  }

  /**
   * Upload a receipt image for a transaction.
   */
  async uploadTransactionReceipt(
    requestParameters: UploadTransactionReceiptRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UploadImageResult> {
    const response = await this.uploadTransactionReceiptRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
