/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  TransactionDraftDto,
  TransactionDraftInputDto,
  UploadImageResult,
} from '../models/index';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TransactionDraftDtoFromJSON,
    TransactionDraftDtoToJSON,
    TransactionDraftInputDtoFromJSON,
    TransactionDraftInputDtoToJSON,
    UploadImageResultFromJSON,
    UploadImageResultToJSON,
} from '../models/index';

export interface AddTransactionDraftRequest {
    transactionDraftInputDto?: TransactionDraftInputDto;
}

export interface DeleteTransactionDraftRequest {
    id: string;
}

export interface GetTransactionDraftRequest {
    id: string;
}

export interface UpdateTransactionDraftRequest {
    transactionDraftId: string;
    transactionDraftInputDto?: TransactionDraftInputDto;
}

export interface UploadTransactionDraftReceiptRequest {
    id: string;
    file?: Blob;
}

/**
 * 
 */
export class TransactionDraftApi extends runtime.BaseAPI {

    /**
     * Creates request options for addTransactionDraft without sending the request
     */
    async addTransactionDraftRequestOpts(requestParameters: AddTransactionDraftRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/transactiondraft`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionDraftInputDtoToJSON(requestParameters['transactionDraftInputDto']),
        };
    }

    /**
     * Add a transaction
     */
    async addTransactionDraftRaw(requestParameters: AddTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDraftDto>> {
        const requestOptions = await this.addTransactionDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDraftDtoFromJSON(jsonValue));
    }

    /**
     * Add a transaction
     */
    async addTransactionDraft(requestParameters: AddTransactionDraftRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDraftDto> {
        const response = await this.addTransactionDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTransactionDraft without sending the request
     */
    async deleteTransactionDraftRequestOpts(requestParameters: DeleteTransactionDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTransactionDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/transactiondraft/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a transaction
     */
    async deleteTransactionDraftRaw(requestParameters: DeleteTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTransactionDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a transaction
     */
    async deleteTransactionDraft(requestParameters: DeleteTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getTransactionDraft without sending the request
     */
    async getTransactionDraftRequestOpts(requestParameters: GetTransactionDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTransactionDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/transactiondraft/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get transaction by id
     */
    async getTransactionDraftRaw(requestParameters: GetTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionDraftDto>> {
        const requestOptions = await this.getTransactionDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionDraftDtoFromJSON(jsonValue));
    }

    /**
     * Get transaction by id
     */
    async getTransactionDraft(requestParameters: GetTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionDraftDto> {
        const response = await this.getTransactionDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTransactionDraft without sending the request
     */
    async updateTransactionDraftRequestOpts(requestParameters: UpdateTransactionDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionDraftId'] == null) {
            throw new runtime.RequiredError(
                'transactionDraftId',
                'Required parameter "transactionDraftId" was null or undefined when calling updateTransactionDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/transactiondraft/{transactionDraftId}`;
        urlPath = urlPath.replace(`{${"transactionDraftId"}}`, encodeURIComponent(String(requestParameters['transactionDraftId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionDraftInputDtoToJSON(requestParameters['transactionDraftInputDto']),
        };
    }

    /**
     * Update a transaction
     */
    async updateTransactionDraftRaw(requestParameters: UpdateTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateTransactionDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a transaction
     */
    async updateTransactionDraft(requestParameters: UpdateTransactionDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateTransactionDraftRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for uploadTransactionDraftReceipt without sending the request
     */
    async uploadTransactionDraftReceiptRequestOpts(requestParameters: UploadTransactionDraftReceiptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadTransactionDraftReceipt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/transactiondraft/{id}/receipt`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Upload a receipt image for a transaction draft.
     */
    async uploadTransactionDraftReceiptRaw(requestParameters: UploadTransactionDraftReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadImageResult>> {
        const requestOptions = await this.uploadTransactionDraftReceiptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadImageResultFromJSON(jsonValue));
    }

    /**
     * Upload a receipt image for a transaction draft.
     */
    async uploadTransactionDraftReceipt(requestParameters: UploadTransactionDraftReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadImageResult> {
        const response = await this.uploadTransactionDraftReceiptRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
