/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailCapabilitiesDto
 */
export interface EmailCapabilitiesDto {
    /**
     * 
     * @type {boolean}
     * @memberof EmailCapabilitiesDto
     */
    emailEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmailCapabilitiesDto
     */
    passwordResetEnabled?: boolean;
}

/**
 * Check if a given object implements the EmailCapabilitiesDto interface.
 */
export function instanceOfEmailCapabilitiesDto(value: object): value is EmailCapabilitiesDto {
    return true;
}

export function EmailCapabilitiesDtoFromJSON(json: any): EmailCapabilitiesDto {
    return EmailCapabilitiesDtoFromJSONTyped(json, false);
}

export function EmailCapabilitiesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailCapabilitiesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'emailEnabled': json['emailEnabled'] == null ? undefined : json['emailEnabled'],
        'passwordResetEnabled': json['passwordResetEnabled'] == null ? undefined : json['passwordResetEnabled'],
    };
}

export function EmailCapabilitiesDtoToJSON(json: any): EmailCapabilitiesDto {
    return EmailCapabilitiesDtoToJSONTyped(json, false);
}

export function EmailCapabilitiesDtoToJSONTyped(value?: EmailCapabilitiesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emailEnabled': value['emailEnabled'],
        'passwordResetEnabled': value['passwordResetEnabled'],
    };
}

