/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupInputDto
 */
export interface GroupInputDto {
    /**
     * 
     * @type {string}
     * @memberof GroupInputDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupInputDto
     */
    photo?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupInputDto
     */
    membersId: Array<string>;
}

/**
 * Check if a given object implements the GroupInputDto interface.
 */
export function instanceOfGroupInputDto(value: object): value is GroupInputDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('membersId' in value) || value['membersId'] === undefined) return false;
    return true;
}

export function GroupInputDtoFromJSON(json: any): GroupInputDto {
    return GroupInputDtoFromJSONTyped(json, false);
}

export function GroupInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'photo': json['photo'] == null ? undefined : json['photo'],
        'membersId': json['membersId'],
    };
}

export function GroupInputDtoToJSON(json: any): GroupInputDto {
    return GroupInputDtoToJSONTyped(json, false);
}

export function GroupInputDtoToJSONTyped(value?: GroupInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'photo': value['photo'],
        'membersId': value['membersId'],
    };
}

