/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface GroupJoinLinkDto
 */
export interface GroupJoinLinkDto {
  /**
   *
   * @type {string}
   * @memberof GroupJoinLinkDto
   */
  groupJoinLinkId: string;
  /**
   *
   * @type {string}
   * @memberof GroupJoinLinkDto
   */
  groupId: string;
}

/**
 * Check if a given object implements the GroupJoinLinkDto interface.
 */
export function instanceOfGroupJoinLinkDto(value: object): value is GroupJoinLinkDto {
  if (!("groupJoinLinkId" in value) || value["groupJoinLinkId"] === undefined) return false;
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  return true;
}

export function GroupJoinLinkDtoFromJSON(json: any): GroupJoinLinkDto {
  return GroupJoinLinkDtoFromJSONTyped(json, false);
}

export function GroupJoinLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupJoinLinkDto {
  if (json == null) {
    return json;
  }
  return {
    groupJoinLinkId: json["groupJoinLinkId"],
    groupId: json["groupId"]
  };
}

export function GroupJoinLinkDtoToJSON(json: any): GroupJoinLinkDto {
  return GroupJoinLinkDtoToJSONTyped(json, false);
}

export function GroupJoinLinkDtoToJSONTyped(
  value?: GroupJoinLinkDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    groupJoinLinkId: value["groupJoinLinkId"],
    groupId: value["groupId"]
  };
}
