/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { GroupBalanceDto } from "./GroupBalanceDto";
import {
  GroupBalanceDtoFromJSON,
  GroupBalanceDtoFromJSONTyped,
  GroupBalanceDtoToJSON,
  GroupBalanceDtoToJSONTyped
} from "./GroupBalanceDto";
import type { SplitzUserReducedDto } from "./SplitzUserReducedDto";
import {
  SplitzUserReducedDtoFromJSON,
  SplitzUserReducedDtoFromJSONTyped,
  SplitzUserReducedDtoToJSON,
  SplitzUserReducedDtoToJSONTyped
} from "./SplitzUserReducedDto";

/**
 *
 * @export
 * @interface GroupDto
 */
export interface GroupDto {
  /**
   *
   * @type {string}
   * @memberof GroupDto
   */
  groupId: string;
  /**
   *
   * @type {string}
   * @memberof GroupDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GroupDto
   */
  photo?: string | null;
  /**
   *
   * @type {Array<SplitzUserReducedDto>}
   * @memberof GroupDto
   */
  members: Array<SplitzUserReducedDto>;
  /**
   *
   * @type {string}
   * @memberof GroupDto
   */
  membersIdHash: string;
  /**
   *
   * @type {Array<GroupBalanceDto>}
   * @memberof GroupDto
   */
  balances: Array<GroupBalanceDto>;
  /**
   * The number of transactions between the user and their friend.
   * This number is only for searching purposes and may not be accurate if transactions are deleted or modified.
   * @type {number}
   * @memberof GroupDto
   */
  transactionCount: number;
  /**
   * The date of the last transaction between the user and their friend.
   * This is only for searching purposes and may not be accurate if transactions are deleted or modified.
   * @type {Date}
   * @memberof GroupDto
   */
  lastActivityTime: Date;
}

/**
 * Check if a given object implements the GroupDto interface.
 */
export function instanceOfGroupDto(value: object): value is GroupDto {
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("members" in value) || value["members"] === undefined) return false;
  if (!("membersIdHash" in value) || value["membersIdHash"] === undefined) return false;
  if (!("balances" in value) || value["balances"] === undefined) return false;
  if (!("transactionCount" in value) || value["transactionCount"] === undefined) return false;
  if (!("lastActivityTime" in value) || value["lastActivityTime"] === undefined) return false;
  return true;
}

export function GroupDtoFromJSON(json: any): GroupDto {
  return GroupDtoFromJSONTyped(json, false);
}

export function GroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDto {
  if (json == null) {
    return json;
  }
  return {
    groupId: json["groupId"],
    name: json["name"],
    photo: json["photo"] == null ? undefined : json["photo"],
    members: (json["members"] as Array<any>).map(SplitzUserReducedDtoFromJSON),
    membersIdHash: json["membersIdHash"],
    balances: (json["balances"] as Array<any>).map(GroupBalanceDtoFromJSON),
    transactionCount: json["transactionCount"],
    lastActivityTime: new Date(json["lastActivityTime"])
  };
}

export function GroupDtoToJSON(json: any): GroupDto {
  return GroupDtoToJSONTyped(json, false);
}

export function GroupDtoToJSONTyped(value?: GroupDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    groupId: value["groupId"],
    name: value["name"],
    photo: value["photo"],
    members: (value["members"] as Array<any>).map(SplitzUserReducedDtoToJSON),
    membersIdHash: value["membersIdHash"],
    balances: (value["balances"] as Array<any>).map(GroupBalanceDtoToJSON),
    transactionCount: value["transactionCount"],
    lastActivityTime: value["lastActivityTime"].toISOString()
  };
}
