/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'

/**
 *
 * @export
 * @interface GroupReducedDto
 */
export interface GroupReducedDto {
  /**
   *
   * @type {string}
   * @memberof GroupReducedDto
   */
  groupId: string
  /**
   *
   * @type {string}
   * @memberof GroupReducedDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof GroupReducedDto
   */
  photo?: string | null
}

/**
 * Check if a given object implements the GroupReducedDto interface.
 */
export function instanceOfGroupReducedDto(value: object): value is GroupReducedDto {
  if (!('groupId' in value) || value['groupId'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  return true
}

export function GroupReducedDtoFromJSON(json: any): GroupReducedDto {
  return GroupReducedDtoFromJSONTyped(json, false)
}

export function GroupReducedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupReducedDto {
  if (json == null) {
    return json
  }
  return {
    groupId: json['groupId'],
    name: json['name'],
    photo: json['photo'] == null ? undefined : json['photo']
  }
}

export function GroupReducedDtoToJSON(json: any): GroupReducedDto {
  return GroupReducedDtoToJSONTyped(json, false)
}

export function GroupReducedDtoToJSONTyped(value?: GroupReducedDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    groupId: value['groupId'],
    name: value['name'],
    photo: value['photo']
  }
}
