/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Group } from "./Group";
import { GroupFromJSON, GroupFromJSONTyped, GroupToJSON, GroupToJSONTyped } from "./Group";

/**
 *
 * @export
 * @interface GroupJoinLink
 */
export interface GroupJoinLink {
  /**
   *
   * @type {string}
   * @memberof GroupJoinLink
   */
  groupJoinLinkId?: string;
  /**
   *
   * @type {string}
   * @memberof GroupJoinLink
   */
  groupId: string;
  /**
   *
   * @type {Group}
   * @memberof GroupJoinLink
   */
  group?: Group;
}

/**
 * Check if a given object implements the GroupJoinLink interface.
 */
export function instanceOfGroupJoinLink(value: object): value is GroupJoinLink {
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  return true;
}

export function GroupJoinLinkFromJSON(json: any): GroupJoinLink {
  return GroupJoinLinkFromJSONTyped(json, false);
}

export function GroupJoinLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupJoinLink {
  if (json == null) {
    return json;
  }
  return {
    groupJoinLinkId: json["groupJoinLinkId"] == null ? undefined : json["groupJoinLinkId"],
    groupId: json["groupId"],
    group: json["group"] == null ? undefined : GroupFromJSON(json["group"])
  };
}

export function GroupJoinLinkToJSON(json: any): GroupJoinLink {
  return GroupJoinLinkToJSONTyped(json, false);
}

export function GroupJoinLinkToJSONTyped(value?: GroupJoinLink | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    groupJoinLinkId: value["groupJoinLinkId"],
    groupId: value["groupId"],
    group: GroupToJSON(value["group"])
  };
}
