/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceStatus } from './InvoiceStatus';
import {
    InvoiceStatusFromJSON,
    InvoiceStatusFromJSONTyped,
    InvoiceStatusToJSON,
    InvoiceStatusToJSONTyped,
} from './InvoiceStatus';
import type { SplitzUserReducedDto } from './SplitzUserReducedDto';
import {
    SplitzUserReducedDtoFromJSON,
    SplitzUserReducedDtoFromJSONTyped,
    SplitzUserReducedDtoToJSON,
    SplitzUserReducedDtoToJSONTyped,
} from './SplitzUserReducedDto';

/**
 * 
 * @export
 * @interface InvoiceReducedDto
 */
export interface InvoiceReducedDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceReducedDto
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceReducedDto
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceReducedDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceReducedDto
     */
    currency: string;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceReducedDto
     */
    createdBy: SplitzUserReducedDto;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceReducedDto
     */
    createTime: Date;
    /**
     * 
     * @type {InvoiceStatus}
     * @memberof InvoiceReducedDto
     */
    status: InvoiceStatus;
}



/**
 * Check if a given object implements the InvoiceReducedDto interface.
 */
export function instanceOfInvoiceReducedDto(value: object): value is InvoiceReducedDto {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function InvoiceReducedDtoFromJSON(json: any): InvoiceReducedDto {
    return InvoiceReducedDtoFromJSONTyped(json, false);
}

export function InvoiceReducedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceReducedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoiceId'],
        'groupId': json['groupId'],
        'name': json['name'] == null ? undefined : json['name'],
        'currency': json['currency'],
        'createdBy': SplitzUserReducedDtoFromJSON(json['createdBy']),
        'createTime': (new Date(json['createTime'])),
        'status': InvoiceStatusFromJSON(json['status']),
    };
}

export function InvoiceReducedDtoToJSON(json: any): InvoiceReducedDto {
    return InvoiceReducedDtoToJSONTyped(json, false);
}

export function InvoiceReducedDtoToJSONTyped(value?: InvoiceReducedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoiceId': value['invoiceId'],
        'groupId': value['groupId'],
        'name': value['name'],
        'currency': value['currency'],
        'createdBy': SplitzUserReducedDtoToJSON(value['createdBy']),
        'createTime': value['createTime'].toISOString(),
        'status': InvoiceStatusToJSON(value['status']),
    };
}

