/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceInputDto
 */
export interface InvoiceInputDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceInputDto
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceInputDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceInputDto
     */
    currency: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvoiceInputDto
     */
    transactionIds: Array<string>;
}

/**
 * Check if a given object implements the InvoiceInputDto interface.
 */
export function instanceOfInvoiceInputDto(value: object): value is InvoiceInputDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('transactionIds' in value) || value['transactionIds'] === undefined) return false;
    return true;
}

export function InvoiceInputDtoFromJSON(json: any): InvoiceInputDto {
    return InvoiceInputDtoFromJSONTyped(json, false);
}

export function InvoiceInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'name': json['name'] == null ? undefined : json['name'],
        'currency': json['currency'],
        'transactionIds': json['transactionIds'],
    };
}

export function InvoiceInputDtoToJSON(json: any): InvoiceInputDto {
    return InvoiceInputDtoToJSONTyped(json, false);
}

export function InvoiceInputDtoToJSONTyped(value?: InvoiceInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupId': value['groupId'],
        'name': value['name'],
        'currency': value['currency'],
        'transactionIds': value['transactionIds'],
    };
}

