/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SplitzUserReducedDto } from './SplitzUserReducedDto';
import {
    SplitzUserReducedDtoFromJSON,
    SplitzUserReducedDtoFromJSONTyped,
    SplitzUserReducedDtoToJSON,
    SplitzUserReducedDtoToJSONTyped,
} from './SplitzUserReducedDto';

/**
 * 
 * @export
 * @interface InvoiceSettlementDto
 */
export interface InvoiceSettlementDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementDto
     */
    invoiceSettlementId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementDto
     */
    invoiceId: string;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceSettlementDto
     */
    fromUser: SplitzUserReducedDto;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceSettlementDto
     */
    toUser: SplitzUserReducedDto;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementDto
     */
    amount: string;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceSettlementDto
     */
    recordedBy: SplitzUserReducedDto;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceSettlementDto
     */
    recordedTime: Date;
}

/**
 * Check if a given object implements the InvoiceSettlementDto interface.
 */
export function instanceOfInvoiceSettlementDto(value: object): value is InvoiceSettlementDto {
    if (!('invoiceSettlementId' in value) || value['invoiceSettlementId'] === undefined) return false;
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('fromUser' in value) || value['fromUser'] === undefined) return false;
    if (!('toUser' in value) || value['toUser'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('recordedBy' in value) || value['recordedBy'] === undefined) return false;
    if (!('recordedTime' in value) || value['recordedTime'] === undefined) return false;
    return true;
}

export function InvoiceSettlementDtoFromJSON(json: any): InvoiceSettlementDto {
    return InvoiceSettlementDtoFromJSONTyped(json, false);
}

export function InvoiceSettlementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceSettlementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceSettlementId': json['invoiceSettlementId'],
        'invoiceId': json['invoiceId'],
        'fromUser': SplitzUserReducedDtoFromJSON(json['fromUser']),
        'toUser': SplitzUserReducedDtoFromJSON(json['toUser']),
        'amount': json['amount'],
        'recordedBy': SplitzUserReducedDtoFromJSON(json['recordedBy']),
        'recordedTime': (new Date(json['recordedTime'])),
    };
}

export function InvoiceSettlementDtoToJSON(json: any): InvoiceSettlementDto {
    return InvoiceSettlementDtoToJSONTyped(json, false);
}

export function InvoiceSettlementDtoToJSONTyped(value?: InvoiceSettlementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoiceSettlementId': value['invoiceSettlementId'],
        'invoiceId': value['invoiceId'],
        'fromUser': SplitzUserReducedDtoToJSON(value['fromUser']),
        'toUser': SplitzUserReducedDtoToJSON(value['toUser']),
        'amount': value['amount'],
        'recordedBy': SplitzUserReducedDtoToJSON(value['recordedBy']),
        'recordedTime': value['recordedTime'].toISOString(),
    };
}

