/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionDto } from './TransactionDto';
import {
    TransactionDtoFromJSON,
    TransactionDtoFromJSONTyped,
    TransactionDtoToJSON,
    TransactionDtoToJSONTyped,
} from './TransactionDto';
import type { InvoiceSettlementDto } from './InvoiceSettlementDto';
import {
    InvoiceSettlementDtoFromJSON,
    InvoiceSettlementDtoFromJSONTyped,
    InvoiceSettlementDtoToJSON,
    InvoiceSettlementDtoToJSONTyped,
} from './InvoiceSettlementDto';
import type { InvoiceStatus } from './InvoiceStatus';
import {
    InvoiceStatusFromJSON,
    InvoiceStatusFromJSONTyped,
    InvoiceStatusToJSON,
    InvoiceStatusToJSONTyped,
} from './InvoiceStatus';
import type { InvoiceDebtDto } from './InvoiceDebtDto';
import {
    InvoiceDebtDtoFromJSON,
    InvoiceDebtDtoFromJSONTyped,
    InvoiceDebtDtoToJSON,
    InvoiceDebtDtoToJSONTyped,
} from './InvoiceDebtDto';
import type { SplitzUserReducedDto } from './SplitzUserReducedDto';
import {
    SplitzUserReducedDtoFromJSON,
    SplitzUserReducedDtoFromJSONTyped,
    SplitzUserReducedDtoToJSON,
    SplitzUserReducedDtoToJSONTyped,
} from './SplitzUserReducedDto';

/**
 * 
 * @export
 * @interface InvoiceDto
 */
export interface InvoiceDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDto
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDto
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDto
     */
    currency: string;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceDto
     */
    createdBy: SplitzUserReducedDto;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceDto
     */
    createTime: Date;
    /**
     * 
     * @type {InvoiceStatus}
     * @memberof InvoiceDto
     */
    status: InvoiceStatus;
    /**
     * 
     * @type {Array<TransactionDto>}
     * @memberof InvoiceDto
     */
    transactions?: Array<TransactionDto>;
    /**
     * 
     * @type {Array<InvoiceDebtDto>}
     * @memberof InvoiceDto
     */
    debts?: Array<InvoiceDebtDto>;
    /**
     * 
     * @type {Array<InvoiceSettlementDto>}
     * @memberof InvoiceDto
     */
    settlements?: Array<InvoiceSettlementDto>;
}



/**
 * Check if a given object implements the InvoiceDto interface.
 */
export function instanceOfInvoiceDto(value: object): value is InvoiceDto {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function InvoiceDtoFromJSON(json: any): InvoiceDto {
    return InvoiceDtoFromJSONTyped(json, false);
}

export function InvoiceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoiceId'],
        'groupId': json['groupId'],
        'name': json['name'] == null ? undefined : json['name'],
        'currency': json['currency'],
        'createdBy': SplitzUserReducedDtoFromJSON(json['createdBy']),
        'createTime': (new Date(json['createTime'])),
        'status': InvoiceStatusFromJSON(json['status']),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(TransactionDtoFromJSON)),
        'debts': json['debts'] == null ? undefined : ((json['debts'] as Array<any>).map(InvoiceDebtDtoFromJSON)),
        'settlements': json['settlements'] == null ? undefined : ((json['settlements'] as Array<any>).map(InvoiceSettlementDtoFromJSON)),
    };
}

export function InvoiceDtoToJSON(json: any): InvoiceDto {
    return InvoiceDtoToJSONTyped(json, false);
}

export function InvoiceDtoToJSONTyped(value?: InvoiceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoiceId': value['invoiceId'],
        'groupId': value['groupId'],
        'name': value['name'],
        'currency': value['currency'],
        'createdBy': SplitzUserReducedDtoToJSON(value['createdBy']),
        'createTime': value['createTime'].toISOString(),
        'status': InvoiceStatusToJSON(value['status']),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(TransactionDtoToJSON)),
        'debts': value['debts'] == null ? undefined : ((value['debts'] as Array<any>).map(InvoiceDebtDtoToJSON)),
        'settlements': value['settlements'] == null ? undefined : ((value['settlements'] as Array<any>).map(InvoiceSettlementDtoToJSON)),
    };
}

