/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceSettlementInputDto
 */
export interface InvoiceSettlementInputDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementInputDto
     */
    fromUserId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementInputDto
     */
    toUserId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettlementInputDto
     */
    amount: string;
}

/**
 * Check if a given object implements the InvoiceSettlementInputDto interface.
 */
export function instanceOfInvoiceSettlementInputDto(value: object): value is InvoiceSettlementInputDto {
    if (!('fromUserId' in value) || value['fromUserId'] === undefined) return false;
    if (!('toUserId' in value) || value['toUserId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function InvoiceSettlementInputDtoFromJSON(json: any): InvoiceSettlementInputDto {
    return InvoiceSettlementInputDtoFromJSONTyped(json, false);
}

export function InvoiceSettlementInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceSettlementInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fromUserId': json['fromUserId'],
        'toUserId': json['toUserId'],
        'amount': json['amount'],
    };
}

export function InvoiceSettlementInputDtoToJSON(json: any): InvoiceSettlementInputDto {
    return InvoiceSettlementInputDtoToJSONTyped(json, false);
}

export function InvoiceSettlementInputDtoToJSONTyped(value?: InvoiceSettlementInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromUserId': value['fromUserId'],
        'toUserId': value['toUserId'],
        'amount': value['amount'],
    };
}

