/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SplitzUserReducedDto } from './SplitzUserReducedDto';
import {
    SplitzUserReducedDtoFromJSON,
    SplitzUserReducedDtoFromJSONTyped,
    SplitzUserReducedDtoToJSON,
    SplitzUserReducedDtoToJSONTyped,
} from './SplitzUserReducedDto';

/**
 * 
 * @export
 * @interface InvoiceDebtDto
 */
export interface InvoiceDebtDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDebtDto
     */
    invoiceId: string;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceDebtDto
     */
    fromUser: SplitzUserReducedDto;
    /**
     * 
     * @type {SplitzUserReducedDto}
     * @memberof InvoiceDebtDto
     */
    toUser: SplitzUserReducedDto;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDebtDto
     */
    amount: string;
}

/**
 * Check if a given object implements the InvoiceDebtDto interface.
 */
export function instanceOfInvoiceDebtDto(value: object): value is InvoiceDebtDto {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('fromUser' in value) || value['fromUser'] === undefined) return false;
    if (!('toUser' in value) || value['toUser'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function InvoiceDebtDtoFromJSON(json: any): InvoiceDebtDto {
    return InvoiceDebtDtoFromJSONTyped(json, false);
}

export function InvoiceDebtDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceDebtDto {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoiceId'],
        'fromUser': SplitzUserReducedDtoFromJSON(json['fromUser']),
        'toUser': SplitzUserReducedDtoFromJSON(json['toUser']),
        'amount': json['amount'],
    };
}

export function InvoiceDebtDtoToJSON(json: any): InvoiceDebtDto {
    return InvoiceDebtDtoToJSONTyped(json, false);
}

export function InvoiceDebtDtoToJSONTyped(value?: InvoiceDebtDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoiceId': value['invoiceId'],
        'fromUser': SplitzUserReducedDtoToJSON(value['fromUser']),
        'toUser': SplitzUserReducedDtoToJSON(value['toUser']),
        'amount': value['amount'],
    };
}

