/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDto
 */
export interface NotificationDto {
    /**
     * 
     * @type {string}
     * @memberof NotificationDto
     */
    notificationId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDto
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDto
     */
    referenceId?: string | null;
    /**
     * 
     * @type {any}
     * @memberof NotificationDto
     */
    data: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDto
     */
    isRead: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDto
     */
    isDismissed: boolean;
    /**
     * 
     * @type {Date}
     * @memberof NotificationDto
     */
    createTime: Date;
}

/**
 * Check if a given object implements the NotificationDto interface.
 */
export function instanceOfNotificationDto(value: object): value is NotificationDto {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('isDismissed' in value) || value['isDismissed'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function NotificationDtoFromJSON(json: any): NotificationDto {
    return NotificationDtoFromJSONTyped(json, false);
}

export function NotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationId': json['notificationId'],
        'type': json['type'],
        'referenceId': json['referenceId'] == null ? undefined : json['referenceId'],
        'data': json['data'],
        'isRead': json['isRead'],
        'isDismissed': json['isDismissed'],
        'createTime': (new Date(json['createTime'])),
    };
}

export function NotificationDtoToJSON(json: any): NotificationDto {
    return NotificationDtoToJSONTyped(json, false);
}

export function NotificationDtoToJSONTyped(value?: NotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notificationId': value['notificationId'],
        'type': value['type'],
        'referenceId': value['referenceId'],
        'data': value['data'],
        'isRead': value['isRead'],
        'isDismissed': value['isDismissed'],
        'createTime': value['createTime'].toISOString(),
    };
}

