/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SplitzUserUpdateViewModel
 */
export interface SplitzUserUpdateViewModel {
  /**
   *
   * @type {string}
   * @memberof SplitzUserUpdateViewModel
   */
  userName?: string | null;
  /**
   *
   * @type {string}
   * @memberof SplitzUserUpdateViewModel
   */
  photo?: string | null;
}

/**
 * Check if a given object implements the SplitzUserUpdateViewModel interface.
 */
export function instanceOfSplitzUserUpdateViewModel(value: object): value is SplitzUserUpdateViewModel {
  return true;
}

export function SplitzUserUpdateViewModelFromJSON(json: any): SplitzUserUpdateViewModel {
  return SplitzUserUpdateViewModelFromJSONTyped(json, false);
}

export function SplitzUserUpdateViewModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SplitzUserUpdateViewModel {
  if (json == null) {
    return json;
  }
  return {
    userName: json["userName"] == null ? undefined : json["userName"],
    photo: json["photo"] == null ? undefined : json["photo"]
  };
}

export function SplitzUserUpdateViewModelToJSON(json: any): SplitzUserUpdateViewModel {
  return SplitzUserUpdateViewModelToJSONTyped(json, false);
}

export function SplitzUserUpdateViewModelToJSONTyped(
  value?: SplitzUserUpdateViewModel | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    userName: value["userName"],
    photo: value["photo"]
  };
}
