/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplitzUserReducedDto
 */
export interface SplitzUserReducedDto {
    /**
     * 
     * @type {string}
     * @memberof SplitzUserReducedDto
     */
    id: string | null;
    /**
     * 
     * @type {string}
     * @memberof SplitzUserReducedDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SplitzUserReducedDto
     */
    photo?: string | null;
}

/**
 * Check if a given object implements the SplitzUserReducedDto interface.
 */
export function instanceOfSplitzUserReducedDto(value: object): value is SplitzUserReducedDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SplitzUserReducedDtoFromJSON(json: any): SplitzUserReducedDto {
    return SplitzUserReducedDtoFromJSONTyped(json, false);
}

export function SplitzUserReducedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplitzUserReducedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'photo': json['photo'] == null ? undefined : json['photo'],
    };
}

export function SplitzUserReducedDtoToJSON(json: any): SplitzUserReducedDto {
    return SplitzUserReducedDtoToJSONTyped(json, false);
}

export function SplitzUserReducedDtoToJSONTyped(value?: SplitzUserReducedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'photo': value['photo'],
    };
}

