/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { SplitzUserReducedDto } from "./SplitzUserReducedDto";
import {
  SplitzUserReducedDtoFromJSON,
  SplitzUserReducedDtoFromJSONTyped,
  SplitzUserReducedDtoToJSON,
  SplitzUserReducedDtoToJSONTyped
} from "./SplitzUserReducedDto";

/**
 *
 * @export
 * @interface TransactionDraftBalanceDto
 */
export interface TransactionDraftBalanceDto {
  /**
   *
   * @type {string}
   * @memberof TransactionDraftBalanceDto
   */
  transactionDraftId?: string;
  /**
   *
   * @type {string}
   * @memberof TransactionDraftBalanceDto
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof TransactionDraftBalanceDto
   */
  balance?: string;
  /**
   *
   * @type {SplitzUserReducedDto}
   * @memberof TransactionDraftBalanceDto
   */
  user: SplitzUserReducedDto;
}

/**
 * Check if a given object implements the TransactionDraftBalanceDto interface.
 */
export function instanceOfTransactionDraftBalanceDto(value: object): value is TransactionDraftBalanceDto {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("user" in value) || value["user"] === undefined) return false;
  return true;
}

export function TransactionDraftBalanceDtoFromJSON(json: any): TransactionDraftBalanceDto {
  return TransactionDraftBalanceDtoFromJSONTyped(json, false);
}

export function TransactionDraftBalanceDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TransactionDraftBalanceDto {
  if (json == null) {
    return json;
  }
  return {
    transactionDraftId: json["transactionDraftId"] == null ? undefined : json["transactionDraftId"],
    userId: json["userId"],
    balance: json["balance"] == null ? undefined : json["balance"],
    user: SplitzUserReducedDtoFromJSON(json["user"])
  };
}

export function TransactionDraftBalanceDtoToJSON(json: any): TransactionDraftBalanceDto {
  return TransactionDraftBalanceDtoToJSONTyped(json, false);
}

export function TransactionDraftBalanceDtoToJSONTyped(
  value?: TransactionDraftBalanceDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    transactionDraftId: value["transactionDraftId"],
    userId: value["userId"],
    balance: value["balance"],
    user: SplitzUserReducedDtoToJSON(value["user"])
  };
}
