/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from '../runtime'
import type { Tag } from './Tag'
import { TagFromJSON, TagFromJSONTyped, TagToJSON, TagToJSONTyped } from './Tag'
import type { TransactionDraftBalanceInputDto } from './TransactionDraftBalanceInputDto'
import {
  TransactionDraftBalanceInputDtoFromJSON,
  TransactionDraftBalanceInputDtoFromJSONTyped,
  TransactionDraftBalanceInputDtoToJSON,
  TransactionDraftBalanceInputDtoToJSONTyped
} from './TransactionDraftBalanceInputDto'

/**
 *
 * @export
 * @interface TransactionDraftInputDto
 */
export interface TransactionDraftInputDto {
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  transactionDraftId?: string
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  groupId?: string | null
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  name?: string | null
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  icon?: string | null
  /**
   *
   * @type {Date}
   * @memberof TransactionDraftInputDto
   */
  createTime?: Date | null
  /**
   *
   * @type {Date}
   * @memberof TransactionDraftInputDto
   */
  transactionTime?: Date | null
  /**
   *
   * @type {number}
   * @memberof TransactionDraftInputDto
   */
  amount?: number | null
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  currency?: string | null
  /**
   *
   * @type {Array<Tag>}
   * @memberof TransactionDraftInputDto
   */
  tags?: Array<Tag>
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  geoCoordinate?: string | null
  /**
   *
   * @type {string}
   * @memberof TransactionDraftInputDto
   */
  photo?: string | null
  /**
   *
   * @type {Array<TransactionDraftBalanceInputDto>}
   * @memberof TransactionDraftInputDto
   */
  balances?: Array<TransactionDraftBalanceInputDto>
}

/**
 * Check if a given object implements the TransactionDraftInputDto interface.
 */
export function instanceOfTransactionDraftInputDto(value: object): value is TransactionDraftInputDto {
  if (!('userId' in value) || value['userId'] === undefined) return false
  return true
}

export function TransactionDraftInputDtoFromJSON(json: any): TransactionDraftInputDto {
  return TransactionDraftInputDtoFromJSONTyped(json, false)
}

export function TransactionDraftInputDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TransactionDraftInputDto {
  if (json == null) {
    return json
  }
  return {
    transactionDraftId: json['transactionDraftId'] == null ? undefined : json['transactionDraftId'],
    userId: json['userId'],
    groupId: json['groupId'] == null ? undefined : json['groupId'],
    name: json['name'] == null ? undefined : json['name'],
    icon: json['icon'] == null ? undefined : json['icon'],
    createTime: json['createTime'] == null ? undefined : new Date(json['createTime']),
    transactionTime: json['transactionTime'] == null ? undefined : new Date(json['transactionTime']),
    amount: json['amount'] == null ? undefined : json['amount'],
    currency: json['currency'] == null ? undefined : json['currency'],
    tags: json['tags'] == null ? undefined : (json['tags'] as Array<any>).map(TagFromJSON),
    geoCoordinate: json['geoCoordinate'] == null ? undefined : json['geoCoordinate'],
    photo: json['photo'] == null ? undefined : json['photo'],
    balances:
      json['balances'] == null
        ? undefined
        : (json['balances'] as Array<any>).map(TransactionDraftBalanceInputDtoFromJSON)
  }
}

export function TransactionDraftInputDtoToJSON(json: any): TransactionDraftInputDto {
  return TransactionDraftInputDtoToJSONTyped(json, false)
}

export function TransactionDraftInputDtoToJSONTyped(
  value?: TransactionDraftInputDto | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    transactionDraftId: value['transactionDraftId'],
    userId: value['userId'],
    groupId: value['groupId'],
    name: value['name'],
    icon: value['icon'],
    createTime: value['createTime'] == null ? undefined : (value['createTime'] as any).toISOString(),
    transactionTime: value['transactionTime'] == null ? undefined : (value['transactionTime'] as any).toISOString(),
    amount: value['amount'],
    currency: value['currency'],
    tags: value['tags'] == null ? undefined : (value['tags'] as Array<any>).map(TagToJSON),
    geoCoordinate: value['geoCoordinate'],
    photo: value['photo'],
    balances:
      value['balances'] == null
        ? undefined
        : (value['balances'] as Array<any>).map(TransactionDraftBalanceInputDtoToJSON)
  }
}
