/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";
import type { Group } from "./Group";
import { GroupFromJSON, GroupFromJSONTyped, GroupToJSON, GroupToJSONTyped } from "./Group";
import type { Tag } from "./Tag";
import { TagFromJSON, TagFromJSONTyped, TagToJSON, TagToJSONTyped } from "./Tag";
import type { TransactionBalance } from "./TransactionBalance";
import {
  TransactionBalanceFromJSON,
  TransactionBalanceFromJSONTyped,
  TransactionBalanceToJSON,
  TransactionBalanceToJSONTyped
} from "./TransactionBalance";

/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  transactionId?: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  groupId: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  icon: string;
  /**
   *
   * @type {Date}
   * @memberof Transaction
   */
  createTime: Date;
  /**
   *
   * @type {Date}
   * @memberof Transaction
   */
  transactionTime: Date;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  currency: string;
  /**
   *
   * @type {Array<Tag>}
   * @memberof Transaction
   */
  tags: Array<Tag>;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  geoCoordinate?: string | null;
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  photo?: string | null;
  /**
   *
   * @type {Group}
   * @memberof Transaction
   */
  group: Group;
  /**
   *
   * @type {Array<TransactionBalance>}
   * @memberof Transaction
   */
  balances?: Array<TransactionBalance>;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
  if (!("groupId" in value) || value["groupId"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("icon" in value) || value["icon"] === undefined) return false;
  if (!("createTime" in value) || value["createTime"] === undefined) return false;
  if (!("transactionTime" in value) || value["transactionTime"] === undefined) return false;
  if (!("amount" in value) || value["amount"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("tags" in value) || value["tags"] === undefined) return false;
  if (!("group" in value) || value["group"] === undefined) return false;
  return true;
}

export function TransactionFromJSON(json: any): Transaction {
  return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
  if (json == null) {
    return json;
  }
  return {
    transactionId: json["transactionId"] == null ? undefined : json["transactionId"],
    groupId: json["groupId"],
    name: json["name"],
    icon: json["icon"],
    createTime: new Date(json["createTime"]),
    transactionTime: new Date(json["transactionTime"]),
    amount: json["amount"],
    currency: json["currency"],
    tags: (json["tags"] as Array<any>).map(TagFromJSON),
    geoCoordinate: json["geoCoordinate"] == null ? undefined : json["geoCoordinate"],
    photo: json["photo"] == null ? undefined : json["photo"],
    group: GroupFromJSON(json["group"]),
    balances: json["balances"] == null ? undefined : (json["balances"] as Array<any>).map(TransactionBalanceFromJSON)
  };
}

export function TransactionToJSON(json: any): Transaction {
  return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    transactionId: value["transactionId"],
    groupId: value["groupId"],
    name: value["name"],
    icon: value["icon"],
    createTime: value["createTime"].toISOString(),
    transactionTime: value["transactionTime"].toISOString(),
    amount: value["amount"],
    currency: value["currency"],
    tags: (value["tags"] as Array<any>).map(TagToJSON),
    geoCoordinate: value["geoCoordinate"],
    photo: value["photo"],
    group: GroupToJSON(value["group"]),
    balances: value["balances"] == null ? undefined : (value["balances"] as Array<any>).map(TransactionBalanceToJSON)
  };
}
