/* tslint:disable */
/* eslint-disable */
/**
 * SplitzBackend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadImageResult
 */
export interface UploadImageResult {
    /**
     * 
     * @type {string}
     * @memberof UploadImageResult
     */
    objectKey?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadImageResult
     */
    contentType?: string;
}

/**
 * Check if a given object implements the UploadImageResult interface.
 */
export function instanceOfUploadImageResult(value: object): value is UploadImageResult {
    return true;
}

export function UploadImageResultFromJSON(json: any): UploadImageResult {
    return UploadImageResultFromJSONTyped(json, false);
}

export function UploadImageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'objectKey': json['objectKey'] == null ? undefined : json['objectKey'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
    };
}

export function UploadImageResultToJSON(json: any): UploadImageResult {
    return UploadImageResultToJSONTyped(json, false);
}

export function UploadImageResultToJSONTyped(value?: UploadImageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectKey': value['objectKey'],
        'contentType': value['contentType'],
    };
}

